angular.module('school-office').factory('RestService',function($resource){
    return {
        'students':$resource('../api/students/:id',{id:'@id'},{
            'save':{
                url:'../api/admin/students',
                method:"POST",
            }
        }),
        'student_username':$resource('../api/students/user/:username',{username:"@username"}),
        'courses':$resource('../api/courses/:id',{id:'@id'}),
        'courses_category':$resource('../api/courses/category/:id',{id:'@id'}),
        'course_selections':$resource('../api/course-selections/:studentNumber',{studentNumber:'@student_number'},{
            'get':{
                isArray:true,
                method:"GET",
            },
            'remove':{
                url:"../api/course-selections/student/:studentNumber/semester/:semester/code/:code",
                method:"DELETE",
                params:{
                    studentNumber:"@student_number",
                    semester:"@semester_id",
                    code:"@code"
                }
            },
            'semester_unscheduled_summary':{
                url:"../api/course-selections/semester/:semester/unscheduled/summary",
                method:"GET",
                params:{
                    semester:"@semester_id"
                },
                isArray:true,
            }
        }),
        'courses_schedule':$resource('../api/course-schedule/semester/:semester',{semester:"@semester_id"},{
            'get_by_weekday':{
                url:'../api/course-schedule/semester/:semester/schedule/:repeat_day',
                method:"GET",
                params:{
                    semester:"@semester_id",
                    repreat_day:"@repeat_day"
                },
                isArray:true,
            },
            'save':{
                url:'../api/admin/course-schedule/semester/:semester/',
                method:"POST",
                params:{
                    semester:"@semester_id"
                }
            }
        }),
        'semesters':$resource('../api/semesters/:id',{id:'@id'},{
            'save':{
                url:'../api/admin/semesters',
                method:"POST"
            },
            'update':{
                url:'../api/admin/semesters',
                method:"PUT",
                params:{}
            },
            'open_register':{
                url:'../api/admin/semesters/:id/open',
                method:'put',
                params:{
                    id:"@id",
                }
            },
            'close_register':{
                url:'../api/admin/semesters/:id/close',
                method:'put',
                params:{
                    id:"@id",
                }
            }
        }),
        'semesters_open':$resource('../api/semester/open',{}),
        'conditions':$resource('../api/conditions/:diploma',{diploma:'@so_diplomas_id'},{
            'get':{
                isArray:true,
                method:"GET",
            }
        })
    };
});
