-- MySQL Script generated by MySQL Workbench
-- 07/25/16 15:54:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema school_office
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `school_office` ;

-- -----------------------------------------------------
-- Schema school_office
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school_office` DEFAULT CHARACTER SET utf8 ;
USE `school_office` ;

-- -----------------------------------------------------
-- Table `school_office`.`so_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_office`.`so_users` ;

CREATE TABLE IF NOT EXISTS `school_office`.`so_users` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `address1` VARCHAR(45) NULL,
  `address2` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `postal_code` VARCHAR(10) NULL,
  `telephone` VARCHAR(20) NULL,
  `role` INT NULL COMMENT '1: student\n2: teacher\n3: admin',
  `token` VARCHAR(45) NULL,
  `token_expire` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `username_UNIQUE` ON `school_office`.`so_users` (`username` ASC);

CREATE UNIQUE INDEX `email_UNIQUE` ON `school_office`.`so_users` (`email` ASC);


-- -----------------------------------------------------
-- Table `school_office`.`so_teachers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_office`.`so_teachers` ;

CREATE TABLE IF NOT EXISTS `school_office`.`so_teachers` (
  `so_users_id` INT NOT NULL,
  PRIMARY KEY (`so_users_id`),
  CONSTRAINT `fk_so_teachers_so_users1`
    FOREIGN KEY (`so_users_id`)
    REFERENCES `school_office`.`so_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_office`.`so_diplomas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_office`.`so_diplomas` ;

CREATE TABLE IF NOT EXISTS `school_office`.`so_diplomas` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_office`.`so_students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_office`.`so_students` ;

CREATE TABLE IF NOT EXISTS `school_office`.`so_students` (
  `student_number` INT NOT NULL,
  `oen` VARCHAR(45) NULL,
  `enter_grade` INT NULL,
  `enter_date` DATE NULL,
  `birthday` DATE NULL,
  `so_users_id` INT NOT NULL,
  `homeroom` INT NOT NULL,
  `so_diplomas_id` INT NOT NULL,
  PRIMARY KEY (`student_number`, `so_diplomas_id`),
  CONSTRAINT `fk_so_students_so_users1`
    FOREIGN KEY (`so_users_id`)
    REFERENCES `school_office`.`so_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_so_students_so_teachers1`
    FOREIGN KEY (`homeroom`)
    REFERENCES `school_office`.`so_teachers` (`so_users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_so_students_so_diplomas1`
    FOREIGN KEY (`so_diplomas_id`)
    REFERENCES `school_office`.`so_diplomas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_so_students_so_users1_idx` ON `school_office`.`so_students` (`so_users_id` ASC);

CREATE INDEX `fk_so_students_so_teachers1_idx` ON `school_office`.`so_students` (`homeroom` ASC);

CREATE INDEX `fk_so_students_so_diplomas1_idx` ON `school_office`.`so_students` (`so_diplomas_id` ASC);


-- -----------------------------------------------------
-- Table `school_office`.`so_course_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_office`.`so_course_categories` ;

CREATE TABLE IF NOT EXISTS `school_office`.`so_course_categories` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_office`.`so_courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_office`.`so_courses` ;

CREATE TABLE IF NOT EXISTS `school_office`.`so_courses` (
  `course_code` VARCHAR(10) NOT NULL,
  `name` VARCHAR(45) NULL,
  `credit` INT NULL DEFAULT 1,
  `grade` INT NULL,
  `so_course_categories_id` INT NOT NULL,
  PRIMARY KEY (`course_code`),
  CONSTRAINT `fk_so_courses_so_course_categories1`
    FOREIGN KEY (`so_course_categories_id`)
    REFERENCES `school_office`.`so_course_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_so_courses_so_course_categories1_idx` ON `school_office`.`so_courses` (`so_course_categories_id` ASC);


-- -----------------------------------------------------
-- Table `school_office`.`so_location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_office`.`so_location` ;

CREATE TABLE IF NOT EXISTS `school_office`.`so_location` (
  `id` INT NOT NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_office`.`so_schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_office`.`so_schedule` ;

CREATE TABLE IF NOT EXISTS `school_office`.`so_schedule` (
  `id` INT NOT NULL,
  `start` DATETIME NULL,
  `end` DATETIME NULL,
  `so_location_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_so_schedule_so_location1`
    FOREIGN KEY (`so_location_id`)
    REFERENCES `school_office`.`so_location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_so_schedule_so_location1_idx` ON `school_office`.`so_schedule` (`so_location_id` ASC);


-- -----------------------------------------------------
-- Table `school_office`.`so_semesters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_office`.`so_semesters` ;

CREATE TABLE IF NOT EXISTS `school_office`.`so_semesters` (
  `id` INT NOT NULL,
  `semester` VARCHAR(45) NULL,
  `open_for_regsiter` TINYINT(1) NULL DEFAULT 0,
  `so_schedule_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_so_semesters_so_schedule1`
    FOREIGN KEY (`so_schedule_id`)
    REFERENCES `school_office`.`so_schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_so_semesters_so_schedule1_idx` ON `school_office`.`so_semesters` (`so_schedule_id` ASC);


-- -----------------------------------------------------
-- Table `school_office`.`so_exam_results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_office`.`so_exam_results` ;

CREATE TABLE IF NOT EXISTS `school_office`.`so_exam_results` (
  `so_courses_course_code` VARCHAR(10) NOT NULL,
  `so_students_student_number` INT NOT NULL,
  `so_semesters_id` INT NOT NULL,
  `grade` INT NULL,
  PRIMARY KEY (`so_courses_course_code`, `so_students_student_number`, `so_semesters_id`),
  CONSTRAINT `fk_so_exam_results_so_courses1`
    FOREIGN KEY (`so_courses_course_code`)
    REFERENCES `school_office`.`so_courses` (`course_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_so_exam_results_so_students1`
    FOREIGN KEY (`so_students_student_number`)
    REFERENCES `school_office`.`so_students` (`student_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_so_exam_results_so_semesters1`
    FOREIGN KEY (`so_semesters_id`)
    REFERENCES `school_office`.`so_semesters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_so_exam_results_so_students1_idx` ON `school_office`.`so_exam_results` (`so_students_student_number` ASC);

CREATE INDEX `fk_so_exam_results_so_semesters1_idx` ON `school_office`.`so_exam_results` (`so_semesters_id` ASC);


-- -----------------------------------------------------
-- Table `school_office`.`so_course_selections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_office`.`so_course_selections` ;

CREATE TABLE IF NOT EXISTS `school_office`.`so_course_selections` (
  `so_students_student_number` INT NOT NULL,
  `so_semesters_id` INT NOT NULL,
  `so_courses_course_code` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`so_students_student_number`, `so_semesters_id`, `so_courses_course_code`),
  CONSTRAINT `fk_so_course_selections_so_students1`
    FOREIGN KEY (`so_students_student_number`)
    REFERENCES `school_office`.`so_students` (`student_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_so_course_selections_so_semesters1`
    FOREIGN KEY (`so_semesters_id`)
    REFERENCES `school_office`.`so_semesters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_so_course_selections_so_courses1`
    FOREIGN KEY (`so_courses_course_code`)
    REFERENCES `school_office`.`so_courses` (`course_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_so_course_selections_so_semesters1_idx` ON `school_office`.`so_course_selections` (`so_semesters_id` ASC);

CREATE INDEX `fk_so_course_selections_so_courses1_idx` ON `school_office`.`so_course_selections` (`so_courses_course_code` ASC);


-- -----------------------------------------------------
-- Table `school_office`.`so_course_schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_office`.`so_course_schedule` ;

CREATE TABLE IF NOT EXISTS `school_office`.`so_course_schedule` (
  `so_schedule_id` INT NOT NULL,
  `so_courses_course_code` VARCHAR(10) NOT NULL,
  `so_semesters_id` INT NOT NULL,
  `so_teachers_so_users_id` INT NOT NULL,
  PRIMARY KEY (`so_schedule_id`, `so_courses_course_code`, `so_semesters_id`, `so_teachers_so_users_id`),
  CONSTRAINT `fk_so_course_schedule_so_schedule1`
    FOREIGN KEY (`so_schedule_id`)
    REFERENCES `school_office`.`so_schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_so_course_schedule_so_courses1`
    FOREIGN KEY (`so_courses_course_code`)
    REFERENCES `school_office`.`so_courses` (`course_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_so_course_schedule_so_semesters1`
    FOREIGN KEY (`so_semesters_id`)
    REFERENCES `school_office`.`so_semesters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_so_course_schedule_so_teachers1`
    FOREIGN KEY (`so_teachers_so_users_id`)
    REFERENCES `school_office`.`so_teachers` (`so_users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_so_course_schedule_so_courses1_idx` ON `school_office`.`so_course_schedule` (`so_courses_course_code` ASC);

CREATE INDEX `fk_so_course_schedule_so_semesters1_idx` ON `school_office`.`so_course_schedule` (`so_semesters_id` ASC);

CREATE INDEX `fk_so_course_schedule_so_teachers1_idx` ON `school_office`.`so_course_schedule` (`so_teachers_so_users_id` ASC);


-- -----------------------------------------------------
-- Table `school_office`.`so_exam_schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_office`.`so_exam_schedule` ;

CREATE TABLE IF NOT EXISTS `school_office`.`so_exam_schedule` (
  `so_schedule_id` INT NOT NULL,
  `so_semesters_id` INT NOT NULL,
  `so_courses_course_code` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`so_schedule_id`, `so_semesters_id`, `so_courses_course_code`),
  CONSTRAINT `fk_so_exam_schedule_so_schedule1`
    FOREIGN KEY (`so_schedule_id`)
    REFERENCES `school_office`.`so_schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_so_exam_schedule_so_semesters1`
    FOREIGN KEY (`so_semesters_id`)
    REFERENCES `school_office`.`so_semesters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_so_exam_schedule_so_courses1`
    FOREIGN KEY (`so_courses_course_code`)
    REFERENCES `school_office`.`so_courses` (`course_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_so_exam_schedule_so_semesters1_idx` ON `school_office`.`so_exam_schedule` (`so_semesters_id` ASC);

CREATE INDEX `fk_so_exam_schedule_so_courses1_idx` ON `school_office`.`so_exam_schedule` (`so_courses_course_code` ASC);


-- -----------------------------------------------------
-- Table `school_office`.`so_graduation_conditions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_office`.`so_graduation_conditions` ;

CREATE TABLE IF NOT EXISTS `school_office`.`so_graduation_conditions` (
  `id` INT NOT NULL,
  `grade` VARCHAR(45) NULL,
  `credit` VARCHAR(45) NULL,
  `so_course_categories_id` INT NOT NULL,
  `so_diplomas_id` INT NOT NULL,
  PRIMARY KEY (`id`, `so_course_categories_id`, `so_diplomas_id`),
  CONSTRAINT `fk_so_graduate_conditions_so_course_categories1`
    FOREIGN KEY (`so_course_categories_id`)
    REFERENCES `school_office`.`so_course_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_so_graduate_conditions_so_diplomas1`
    FOREIGN KEY (`so_diplomas_id`)
    REFERENCES `school_office`.`so_diplomas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_so_graduate_conditions_so_course_categories1_idx` ON `school_office`.`so_graduation_conditions` (`so_course_categories_id` ASC);

CREATE INDEX `fk_so_graduate_conditions_so_diplomas1_idx` ON `school_office`.`so_graduation_conditions` (`so_diplomas_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
